### ISSUE TITLE
Support search_with_capped_res DISC evaluations

### ISSUE THREAD

**Issue by shubhamjain0594** [facebookresearch/sscd-copy-detection#1] opened 2022-04-17 18:53 UTC
Hello,

I have been looking at reproducing the model and it feels the [code](https://github.com/facebookresearch/sscd-copy-detection/blob/550e40cab3820784278fa34c87965c55e4dc5e0a/sscd/datasets/disc.py#L104) for evaluation of uAP includes only top 10 nearest neighbours. 

While the uAP as calculated in [ISC competition](https://github.com/facebookresearch/isc2021/blob/main/scripts/compute_metrics.py#L73) I believe used around 500K nearest neighbours. I am not sure of the impact of the value, but it might lead to overestimation of uAP.

**Comment by edpizzi** [comment] 2022-04-18 16:18
Hi Shubham, thanks for your interest in our work!

10 results per query also produces 500k candidates, since there are 50k queries, and 50k * 10 = 500k. That said, our approach allocates candidates less flexibly.

I'll look into making a diff to support the max total candidates setting.

Ed

**Comment by edpizzi** [comment] 2022-04-19 18:37
I did an initial experiment using the `sscd_disc_mixup` and `sscd_imagenet_mixup` models, for which I already had features extracted.

For `sscd_disc_mixup`, I find a -0.5% regression in &micro;AP when using 500k global candidates (versus k=10 per query), and no difference (-0.02%) in score normalized &micro;AP (&micro;APSN).

For an ImageNet trained model (`sscd_imagenet_mixup`), it makes a more significant difference: -1.9% &micro;AP but still no difference (-0.03%) with score normalization. I assume this is because ImageNet models have worse calibration on DISC without score normalization.

For the paper, we evaluate all methods using the same settings, which is K=10 KNN. This is different from the competition setting, but shouldn't significantly change score normalized results.

**Comment by edpizzi** [comment] 2022-08-02 01:22
Merged a diff to implement this. Marking as closed.

**Closed by edpizzi** 2022-08-02 01:22 UTC
